import ReactQueryProvider from '@/providers/ReactQueryProvider'
import { AppRouterCacheProvider } from '@mui/material-nextjs/v13-appRouter';
import type { Metadata } from 'next'
import { ThemeProvider } from '@mui/material/styles';
import {TextField, CssBaseline} from '@mui/material'
import JotaiProvider from '@/providers/JotaiProvider';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <JotaiProvider>
        <AppRouterCacheProvider>
          <CssBaseline/>
        <ReactQueryProvider>
          {children}
        </ReactQueryProvider>
        </AppRouterCacheProvider>
        </JotaiProvider>
        </body>
    </html>
  )
}
